FROM 853972537351.dkr.ecr.ca-central-1.amazonaws.com/cruddur-python:latest

WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

#ENV FLASK_DEBUG=1

EXPOSE ${PORT}


CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567", "--no-debugger", "--no-reload"]
